"""phase4 decision provenance: risk_events table + trades snapshot columns

Revision ID: 74d594c281a5
Revises: 17ac6904264d
Create Date: 2026-08-08 14:20:53.743197

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '74d594c281a5'
down_revision: Union[str, None] = '17ac6904264d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mt5_account_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('codes', sa.Text(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('intended_lots', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('degrade_level', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mt5_account_id'], ['mt5_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_mt5_account_id'), ['mt5_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_stage'), ['stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_risk_evt_acct_time', ['mt5_account_id', 'created_at'], unique=False)
        batch_op.create_index('ix_risk_evt_user_time', ['user_id', 'created_at'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chronos_vote', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('q_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('degrade_level', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('decision_snapshot', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('decision_snapshot')
        batch_op.drop_column('degrade_level')
        batch_op.drop_column('q_score')
        batch_op.drop_column('chronos_vote')

    with op.batch_alter_table('risk_events', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_evt_user_time')
        batch_op.drop_index('ix_risk_evt_acct_time')
        batch_op.drop_index(batch_op.f('ix_risk_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_stage'))
        batch_op.drop_index(batch_op.f('ix_risk_events_mt5_account_id'))
        batch_op.drop_index(batch_op.f('ix_risk_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_risk_events_created_at'))

    op.drop_table('risk_events')
    # ### end Alembic commands ###
