"""phase8 license activation tables

Revision ID: 80d68481667f
Revises: 74d594c281a5
Create Date: 2026-08-08 15:45:04.105274

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '80d68481667f'
down_revision: Union[str, None] = '74d594c281a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('license_key', sa.String(length=40), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('max_accounts', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('machine_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('bound_factors', sa.Text(), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_error', sa.String(length=200), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licenses_license_key'), ['license_key'], unique=True)

    op.create_table('license_activations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('license_key', sa.String(length=40), nullable=False),
    sa.Column('mt5_login', sa.String(length=32), nullable=False),
    sa.Column('mt5_account_id', sa.String(length=36), nullable=True),
    sa.Column('machine_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mt5_account_id'], ['mt5_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('license_activations', schema=None) as batch_op:
        batch_op.create_index('ix_lic_act_key_login', ['license_key', 'mt5_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_activations_license_key'), ['license_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_activations_mt5_account_id'), ['mt5_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_activations_mt5_login'), ['mt5_login'], unique=False)
        batch_op.create_index(batch_op.f('ix_license_activations_revoked'), ['revoked'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('license_activations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_license_activations_revoked'))
        batch_op.drop_index(batch_op.f('ix_license_activations_mt5_login'))
        batch_op.drop_index(batch_op.f('ix_license_activations_mt5_account_id'))
        batch_op.drop_index(batch_op.f('ix_license_activations_license_key'))
        batch_op.drop_index('ix_lic_act_key_login')

    op.drop_table('license_activations')
    with op.batch_alter_table('licenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licenses_license_key'))

    op.drop_table('licenses')
    # ### end Alembic commands ###
