"""baseline schema

Revision ID: 17ac6904264d
Revises: 
Create Date: 2026-08-07 19:35:14.765113

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '17ac6904264d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_key', sa.String(length=1000), nullable=False),
    sa.Column('encrypted_secret', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('monthly_tokens', sa.Integer(), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('monthly_reset_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('mt5_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('server', sa.String(length=100), nullable=False),
    sa.Column('terminal_path', sa.String(length=500), nullable=True),
    sa.Column('account_type', sa.Enum('DEMO', 'REAL', name='accounttype'), nullable=True),
    sa.Column('status', sa.Enum('CONNECTING', 'ONLINE', 'OFFLINE', 'ERROR', name='accountstatus'), nullable=True),
    sa.Column('status_message', sa.String(length=500), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('equity', sa.Float(), nullable=True),
    sa.Column('margin', sa.Float(), nullable=True),
    sa.Column('margin_level', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('is_trading_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_market_primary', sa.Boolean(), nullable=True),
    sa.Column('is_connected', sa.Boolean(), nullable=True),
    sa.Column('last_connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mt5_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mt5_accounts_user_id'), ['user_id'], unique=False)

    op.create_table('ai_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mt5_account_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detail', sa.String(length=300), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mt5_account_id'], ['mt5_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_activities', schema=None) as batch_op:
        batch_op.create_index('ix_act_user_time', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activities_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activities_mt5_account_id'), ['mt5_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_activities_user_id'), ['user_id'], unique=False)

    op.create_table('evolution_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mt5_account_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject', sa.String(length=40), nullable=True),
    sa.Column('before_value', sa.String(length=40), nullable=True),
    sa.Column('after_value', sa.String(length=40), nullable=True),
    sa.Column('delta', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('meta_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mt5_account_id'], ['mt5_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evolution_logs', schema=None) as batch_op:
        batch_op.create_index('ix_evo_user_time', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolution_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolution_logs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolution_logs_mt5_account_id'), ['mt5_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evolution_logs_user_id'), ['user_id'], unique=False)

    op.create_table('strategy_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mt5_account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('max_positions', sa.Integer(), nullable=True),
    sa.Column('ai_mode', sa.String(length=20), nullable=True),
    sa.Column('decision_interval', sa.Integer(), nullable=True),
    sa.Column('max_position_lots', sa.Float(), nullable=True),
    sa.Column('max_daily_loss_pct', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('max_spread_points', sa.Integer(), nullable=True),
    sa.Column('max_risk_per_trade_pct', sa.Float(), nullable=True),
    sa.Column('min_confidence', sa.Float(), nullable=True),
    sa.Column('trade_asian', sa.Boolean(), nullable=True),
    sa.Column('trade_european', sa.Boolean(), nullable=True),
    sa.Column('trade_american', sa.Boolean(), nullable=True),
    sa.Column('auto_evolution', sa.Boolean(), nullable=True),
    sa.Column('base_capital', sa.Float(), nullable=True),
    sa.Column('sizing_mode', sa.String(length=20), nullable=True),
    sa.Column('volatility_factor', sa.Float(), nullable=True),
    sa.Column('same_direction_decay', sa.Float(), nullable=True),
    sa.Column('min_lot_per_trade', sa.Float(), nullable=True),
    sa.Column('max_lot_per_trade', sa.Float(), nullable=True),
    sa.Column('max_concurrent_same_direction', sa.Integer(), nullable=True),
    sa.Column('open_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('capital_source', sa.String(length=12), nullable=True),
    sa.Column('smart_tp_enabled', sa.Boolean(), nullable=True),
    sa.Column('tp1_atr_mult', sa.Float(), nullable=True),
    sa.Column('tp1_close_pct', sa.Float(), nullable=True),
    sa.Column('tp2_atr_mult', sa.Float(), nullable=True),
    sa.Column('tp2_close_pct', sa.Float(), nullable=True),
    sa.Column('tp3_atr_mult', sa.Float(), nullable=True),
    sa.Column('tp3_close_pct', sa.Float(), nullable=True),
    sa.Column('breakeven_after_tp1', sa.Boolean(), nullable=True),
    sa.Column('breakeven_buffer_points', sa.Float(), nullable=True),
    sa.Column('trailing_atr_mult', sa.Float(), nullable=True),
    sa.Column('trailing_activate_after_tp2', sa.Boolean(), nullable=True),
    sa.Column('ai_reverse_close_confidence', sa.Float(), nullable=True),
    sa.Column('follow_leader', sa.Boolean(), nullable=True),
    sa.Column('sizing_scale_mode', sa.String(length=8), nullable=True),
    sa.Column('regime_open_mode', sa.String(length=8), nullable=True),
    sa.Column('short_guard_mode', sa.String(length=8), nullable=True),
    sa.Column('reversal_confirm_cycles', sa.Integer(), nullable=True),
    sa.Column('basket_tp_amount', sa.Float(), nullable=True),
    sa.Column('enable_l3_guard', sa.Boolean(), nullable=True),
    sa.Column('enable_trailing_sl', sa.Boolean(), nullable=True),
    sa.Column('enable_hard_loss_cut', sa.Boolean(), nullable=True),
    sa.Column('hard_loss_basket_amount', sa.Float(), nullable=True),
    sa.Column('hard_loss_per_trade_amount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mt5_account_id'], ['mt5_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mt5_account_id')
    )
    with op.batch_alter_table('strategy_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_configs_user_id'), ['user_id'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mt5_account_id', sa.String(length=36), nullable=False),
    sa.Column('mt5_ticket', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('sl', sa.Float(), nullable=True),
    sa.Column('tp', sa.Float(), nullable=True),
    sa.Column('profit', sa.Float(), nullable=True),
    sa.Column('commission', sa.Float(), nullable=True),
    sa.Column('swap', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('deepseek_decision', sa.String(length=20), nullable=True),
    sa.Column('deepseek_confidence', sa.Float(), nullable=True),
    sa.Column('deepseek_reasoning', sa.Text(), nullable=True),
    sa.Column('hunyuan_decision', sa.String(length=20), nullable=True),
    sa.Column('hunyuan_confidence', sa.Float(), nullable=True),
    sa.Column('hunyuan_reasoning', sa.Text(), nullable=True),
    sa.Column('debate_summary', sa.Text(), nullable=True),
    sa.Column('meta_agent_decision', sa.String(length=20), nullable=True),
    sa.Column('meta_agent_confidence', sa.Float(), nullable=True),
    sa.Column('risk_check_passed', sa.Boolean(), nullable=True),
    sa.Column('mfe', sa.Float(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.Column('open_time', sa.DateTime(), nullable=True),
    sa.Column('close_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mt5_account_id'], ['mt5_accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_mt5_account_id'), ['mt5_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_trades_mt5_account_id'))

    op.drop_table('trades')
    with op.batch_alter_table('strategy_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_configs_user_id'))

    op.drop_table('strategy_configs')
    with op.batch_alter_table('evolution_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evolution_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_evolution_logs_mt5_account_id'))
        batch_op.drop_index(batch_op.f('ix_evolution_logs_kind'))
        batch_op.drop_index(batch_op.f('ix_evolution_logs_created_at'))
        batch_op.drop_index('ix_evo_user_time')

    op.drop_table('evolution_logs')
    with op.batch_alter_table('ai_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_activities_mt5_account_id'))
        batch_op.drop_index(batch_op.f('ix_ai_activities_kind'))
        batch_op.drop_index(batch_op.f('ix_ai_activities_created_at'))
        batch_op.drop_index('ix_act_user_time')

    op.drop_table('ai_activities')
    with op.batch_alter_table('mt5_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mt5_accounts_user_id'))

    op.drop_table('mt5_accounts')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
